// Generated by BUCKLESCRIPT VERSION 5.0.1, PLEASE EDIT WITH CARE

import * as React from "react";

function App(Props) {
  return React.createElement("div", undefined, "Cities");
}

var make = App;

export {
  make ,
  
}
/* react Not a pure module */
