// Generated by BUCKLESCRIPT VERSION 5.0.1, PLEASE EDIT WITH CARE


var cities = /* :: */[
  /* record */[
    /* id */"34a8c685-6088-4eed-bd58-3769b1a408ba",
    /* name */"Vienna",
    /* coordinates : record */[
      /* lat */48.2,
      /* lng */16.366667
    ],
    /* image : record */[
      /* url */"/assets/vienna.jpg",
      /* attribution */"CC BY 3.0: Of the individual pictures, Gryffindor (Wikipedia), of the panorama, Roland Geider",
      /* attributionUrl */"https://commons.wikimedia.org/wiki/File:Stephansdom_Vienna_July_2008_(27)-Stephansdom_Vienna_July_2008_(31).jpg"
    ]
  ],
  /* :: */[
    /* record */[
      /* id */"675a1180-62cc-4518-b272-a0e1beeaf868",
      /* name */"New York",
      /* coordinates : record */[
        /* lat */40.7127,
        /* lng */-74.0059
      ],
      /* image : record */[
        /* url */"/assets/new-york.jpg",
        /* attribution */"CC BY-SA 4.0: Siddarth Hanumanthu",
        /* attributionUrl */"https://commons.wikimedia.org/wiki/File:1650_Grand_Concourse.jpg"
      ]
    ],
    /* :: */[
      /* record */[
        /* id */"873da18c-4eb4-4cd1-8edf-d0bcc5776127",
        /* name */"Denver",
        /* coordinates : record */[
          /* lat */39.76185,
          /* lng */-104.881105
        ],
        /* image : record */[
          /* url */"/assets/denver.jpg",
          /* attribution */"Public Domain",
          /* attributionUrl */"https://commons.wikimedia.org/wiki/File:Denver_from_Highlands.jpg"
        ]
      ],
      /* [] */0
    ]
  ]
];

export {
  cities ,
  
}
/* No side effect */
