// Generated by BUCKLESCRIPT VERSION 5.0.1, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ReactDOMRe from "reason-react/src/ReactDOMRe.js";
import * as App$ReactTemplate from "./App.bs.js";
import * as GlobalStyles$ReactTemplate from "./GlobalStyles.bs.js";

ReactDOMRe.renderToElementWithId(React.createElement(App$ReactTemplate.make, { }), "root");

export {
  
}
/*  Not a pure module */
